# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: pipenv-setup-sync
    name: "pipenv-setup sync with pipfile"
    stages: [push]
    language: system
    types: [python]
    entry: python -m pipenv_setup sync --pipfile
    pass_filenames: false
    always_run: true

  - id: pipenv-setup-check
    name: "pipenv-setup check"
    stages: [push]
    language: system
    types: [python]
    entry: python -m pipenv_setup check
    pass_filenames: false
    always_run: true
